"""
retrieval.py

Performs cosine similarity search against the pgvector chunks table.
Takes an embedded query vector and returns the top-K most relevant chunks
along with their parent document metadata.
"""

import logging
from typing import List

from .database import get_db_connection, _rows_to_dicts

logger = logging.getLogger(__name__)

# Number of chunks to return per query
TOP_K = 5


def retrieve_top_chunks(query_vector: List[float]) -> list:
    """
    Runs a cosine similarity search against the chunks table using pgvector's
    <=> operator (cosine distance). Returns the TOP_K most relevant chunks,
    joined with their parent document's filename.

    Args:
        query_vector: A 768-dimensional float vector representing the embedded
                      user query, generated by embeddings.embed_query().

    Returns:
        List of dicts, each containing:
            - chunk_id (str)
            - document_id (str)
            - chunk_text (str): Human-readable text used as LLM context.
            - embed_text (str): Text used to generate the embedding.
            - page_number (int | None)
            - metadata (dict)
            - filename (str): From the joined documents table.
            - similarity (float): Cosine similarity score (1 = identical).

    Raises:
        Exception: Re-raises any database error after logging.
    """
    logger.info("Running cosine similarity retrieval (top %d chunks).", TOP_K)

    # Convert the Python list to the pgvector string format: '[x1,x2,...,xN]'
    vector_str = "[" + ",".join(str(v) for v in query_vector) + "]"

    try:
        with get_db_connection() as conn:
            cur = conn.cursor()
            cur.execute(
                """
                SELECT
                    c.chunk_id::text,
                    c.document_id::text,
                    c.chunk_text,
                    c.embed_text,
                    c.page_number,
                    c.metadata,
                    d.filename,
                    1 - (c.embedding <=> %s::vector) AS similarity
                FROM chunks c
                JOIN documents d ON c.document_id = d.document_id
                WHERE d.status = 'complete'
                ORDER BY c.embedding <=> %s::vector
                LIMIT %s
                """,
                (vector_str, vector_str, TOP_K),
            )
            results = _rows_to_dicts(cur)

        logger.info(
            "Retrieval complete. Returned %d chunks. Top similarity: %.4f",
            len(results),
            results[0]["similarity"] if results else 0.0,
        )
        return results

    except Exception:
        logger.exception("Error during chunk retrieval.")
        raise
